---
title: "covid-19"
author: "JW Parrish"
date: "1/07/2022"
output: html_document
---

## Methods for Developing COVID Models


**Background**    

The initial phase of the COVID-19 epidemic indicated exponential growth potential both worldwide and locally. This suggests that without intervention, infections would grow and then decay exponentially. This sparked the motivation for instituting efforts to “flatten the curve”. While multiple efforts have been made to predict the long-term trajectory of COVID-19, using deterministic and stochastic based methods, they all require heavy assumptions with unknown accuracy. As we learn more about the etiology of the disease and its transmissibility, these long-term models will be refined.
Although long-term forecasting is evolving, short-term forecasting built upon simple models using basic assumptions are critical for documenting and identifying changes in our trajectory.[[1]](#references) These short-term models can assist us with monitoring the impact of implementing and relaxing health mandates to inform our public health efforts; simply put, we can monitor how things are progressing.


**Methods**   

We used the incidence[[2]](#references) package in R[[3]](#references) to model the short term epidemic trajectory using a log-linear model under the form:

log(y) = r*t+b

Where, ‘y’ is the daily incidence, ‘t’ is the time in days from the start of the outbreak, ‘r’ is the growth rate, and ‘b’ is the origin or intercept. 

Assuming that without mitigation efforts the disease will spread at an exponential rate, we modeled the observed daily case counts over a 21-day period (daily counts) or 10-day period (cumulative counts) based on a simulated date of onset distribution, and projected out 12-15 days (depending on model). Due to the delay between an individual recognizing symptoms, being tested, those results being reported to the State and entered into the system and the growing number of cases, tracking onset date explicitly has become difficult. To estimate the onset date distribution from daily reports we sampled from the 10% of reported cases with a known onset date to inform our model parameters. 
Distribution creation  

1. We simulated a truncated gamma distribution with a median of 4 days and range of 0 – 12 days. The randomly sampled lag days for each reported case.  The lag days were subtracted from the report date to create an estimated onset date distribution.    

2. Due to improvements in detection and reporting we shortened the truncation window from 9 to 5 days. The model uses the 21 day period (for daily case projection) or 10 day period (for cumulative case projections prior to the truncation window.  

3. We implemented a new method for estimating preliminary counts based on partial information from the truncation window. Using the projections and distcrete packages in R built by the R Epidemics Consortium (RECON) [[4]](#references), we simulated the incidence using the measured effective reproductive number at truncation,  and mean serial interval distribution from a base Poisson distribution. These estimated values (while excluded from the model) are represented with gray bars (daily plot) or dots (cumulative plot). The estimate with 0.25 and 0.975 credible intervals are provided.  

4. Using the log-linear model based on the 21-day or 10-day pre-truncation window we project out 12 days (7 days past the lag window).  The use of this 21 day or 10 day window for the statewide estimate was chosen by convention with short-term projections, where the assumption is that more recent trends likely better approximate the current trajectory. We shortened the window from 30 to 21 days to increase the sensitivity in reacting to changes in the trend. This change however increases the imprecision of these estimates. 

These methods are validated against other more complex methods bi-weekly that explicitly account for reporting delay distribution, generation time distribution, and incubation period distribution using the EpiNow2 package in R [[5]](#references). These methods are only ran bi-weekly due to the computing resources required to complete them.   

The code for imputing an onset date from report date:  
```{r eval = FALSE}

set.seed(2020)
dist <- round(rtgamma(100000, shape =  4, truncation = 12))

set.seed(19)

dat$duration_imp1 <- sample(dist, nrow(dat))

dat$OnsetDate_imp <- as.Date(dat$ReportDate - dat$duration_imp1, origin = "1970-01-01")

dat1 <- dat
```


**Interpretation**    

The first plot is based on daily incremental incidence counts often called the epidemic curve. The second plot is the daily cumulative counts of new cases. Both plots use the simulated date of onset. We’ve used gray bars (epidemic curve plot) and gray dots (cumulative incidence plot) to denote the truncated date from the model fit.

Generally, when the daily epidemic curve plot trajectory is decreasing, this means the number of new daily onset cases is getting smaller, suggesting the mitigation strategies are having an impact or the disease is dying out. Likewise, when the cumulative incidence trajectory flattens and appears more linear, this indicates a reduction in the number of new cases added to the total each day. 

The difference in confidence bands (indicated by the band) are related to the amount of variability between the numbers. With cumulative case counts much less variability is observed compared to daily case counts, resulting in less residual error between observations and smaller bands.  

These short term forecasts will update daily and project an estimated exponential trajectory. Watching how daily observations compare to these trajectories can provide information about whether the course of the epidemic in Alaska remains on the same track or whether it is growing or declining more quickly or more slowly than previously observed.


**References**  

[[1]](https://doi.org/10.1016/j.epidem.2017.02.012) Nouvellet, P., Cori, A., Garske, T., Blake, I.M., Dorigatti, I., Hinsley, W., Jombart, T., Mills, H.L., Nedjati-Gilani, G., Kerkhove, M.D.V., Fraser, C., Donnelly, C.A., Ferguson, N.M. and Riley, S., A simple approach to measure transmissibility and forecast incidence, 2018. Epidemics, Vol 22, pp. 29 - 35.)

[[2]](https://doi.org/10.5281/zenodo.2584018) Thibaut Jombart, Zhian N. Kamvar, Rich FitzJohn, Jun Cai, Sangeeta Bhatia, Jakob
Schumacher and Juliet R.C. Pulliam (2020). incidence: Compute, Handle, Plot and Model
Incidence of Dated Events. R package version 1.7.1.

[[3]](https://www.r-project.org/) R: A Language and Environment for Statistical Computing, R Core Team, 2019.    

[[4]](https://www.repidemicsconsortium.org/) R Epidemics Consortium (RECON)

[[5]](https://epiforecasts.io/EpiNow2/) Abbott S, Hellewell J, Hickson J, Munday J, Gostic K, Ellis P, Sherratt K, Gibbs H, Thompson R, Meakin S, Bosse N, Mee P, Funk S (2020). EpiNow2: Estimate Real-Time Case Counts and Time-Varying Epidemiological Parameters.

**Note:**  
The code that created this application is available at:   
<https://github.com/AK-MCH-EPI/AK_COVID>  
last updated: 2021-01-07 
